"""Build the upload-ready Data Vortex 2026 Round 1 Phase 2 package.

The source database is opened read-only.  All submitted numbers are generated
from the three SELECT statements defined in this file and verified before the
PDF and JPEG artifacts are written.
"""

from __future__ import annotations

import os
import sqlite3
import textwrap
from pathlib import Path
from typing import Iterable, Sequence

from PIL import Image, ImageDraw, ImageFont
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    LongTable,
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATABASE_PATH = PROJECT_ROOT / "data" / "data_vortex.db"
SUBMISSION_DIR = PROJECT_ROOT / "submission"

QUESTIONS = {
    "easy": {
        "id": "E2 - Most Engaged Posts",
        "difficulty": "Easy",
        "question": (
            "Find the top 10 posts based on total engagement. Total engagement is "
            "defined as likes + shares + comments. Ignore posts where likes are missing."
        ),
        "sql": """SELECT
    p.post_id,
    p.user_id,
    p.platform,
    p.likes,
    p.shares,
    p.comments,
    p.likes + p.shares + p.comments AS total_engagement
FROM posts AS p
WHERE p.likes IS NOT NULL
ORDER BY total_engagement DESC, p.post_id ASC
LIMIT 10;""",
    },
    "medium": {
        "id": "M1 - Which Locations Generate the Most Engagement?",
        "difficulty": "Medium",
        "question": (
            "Using both datasets, calculate the total engagement generated by users from "
            "each location. Return the location, number of posts, and total engagement. "
            "Rank locations from highest to lowest engagement."
        ),
        "sql": """SELECT
    u.location,
    COUNT(p.post_id) AS post_count,
    SUM(p.likes + p.shares + p.comments) AS total_engagement
FROM users AS u
JOIN posts AS p
    ON p.user_id = u.user_id
WHERE p.likes IS NOT NULL
GROUP BY u.location
ORDER BY total_engagement DESC, u.location ASC;""",
    },
    "hard": {
        "id": "H2 - Rank Users Within Their Location",
        "difficulty": "Hard",
        "question": (
            "For every location, rank users based on their total engagement. Return only "
            "the top 3 users from each location."
        ),
        "sql": """WITH user_engagement AS (
    SELECT
        u.user_id,
        u.location,
        u.follower_count,
        COUNT(p.post_id) AS post_count,
        SUM(p.likes + p.shares + p.comments) AS total_engagement
    FROM users AS u
    JOIN posts AS p
        ON p.user_id = u.user_id
    WHERE p.likes IS NOT NULL
    GROUP BY u.user_id, u.location, u.follower_count
), ranked_users AS (
    SELECT
        user_id,
        location,
        follower_count,
        post_count,
        total_engagement,
        DENSE_RANK() OVER (
            PARTITION BY location
            ORDER BY total_engagement DESC
        ) AS engagement_rank
    FROM user_engagement
)
SELECT
    location,
    engagement_rank,
    user_id,
    follower_count,
    post_count,
    total_engagement
FROM ranked_users
WHERE engagement_rank <= 3
ORDER BY location ASC, engagement_rank ASC, user_id ASC;""",
    },
}


def read_only_connection() -> sqlite3.Connection:
    """Open the project database in SQLite read-only mode."""
    uri = f"file:{DATABASE_PATH.as_posix()}?mode=ro"
    return sqlite3.connect(uri, uri=True)


def execute_query(conn: sqlite3.Connection, sql: str) -> tuple[list[str], list[tuple]]:
    cursor = conn.execute(sql)
    columns = [item[0] for item in cursor.description]
    return columns, cursor.fetchall()


def validate_results(conn: sqlite3.Connection, results: dict[str, tuple[list[str], list[tuple]]]) -> None:
    """Reconcile output totals and rankings without modifying the source DB."""
    easy_columns, easy_rows = results["easy"]
    medium_columns, medium_rows = results["medium"]
    hard_columns, hard_rows = results["hard"]

    assert len(easy_rows) == 10 and easy_columns[-1] == "total_engagement"
    assert all(row[3] is not None for row in easy_rows)
    assert all(
        easy_rows[index][-1] >= easy_rows[index + 1][-1]
        for index in range(len(easy_rows) - 1)
    )

    posts_with_likes, direct_total = conn.execute(
        """SELECT COUNT(*), SUM(likes + shares + comments)
           FROM posts WHERE likes IS NOT NULL"""
    ).fetchone()
    assert sum(row[1] for row in medium_rows) == posts_with_likes
    assert sum(row[2] for row in medium_rows) == direct_total
    assert medium_columns == ["location", "post_count", "total_engagement"]

    expected_hard_rows = conn.execute(
        """SELECT SUM(CASE WHEN user_count >= 3 THEN 3 ELSE user_count END)
           FROM (
               SELECT u.location, COUNT(DISTINCT p.user_id) AS user_count
               FROM users AS u
               JOIN posts AS p ON p.user_id = u.user_id
               WHERE p.likes IS NOT NULL
               GROUP BY u.location
           )"""
    ).fetchone()[0]
    assert len(hard_rows) == expected_hard_rows
    assert all(1 <= row[1] <= 3 for row in hard_rows)
    assert hard_columns == [
        "location",
        "engagement_rank",
        "user_id",
        "follower_count",
        "post_count",
        "total_engagement",
    ]


def styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "Title", parent=base["Title"], alignment=TA_CENTER, fontSize=22,
            leading=28, textColor=colors.HexColor("#172B4D"), spaceAfter=16,
        ),
        "subtitle": ParagraphStyle(
            "Subtitle", parent=base["Normal"], alignment=TA_CENTER, fontSize=11,
            leading=15, textColor=colors.HexColor("#4A5568"), spaceAfter=20,
        ),
        "h1": ParagraphStyle(
            "H1", parent=base["Heading1"], fontSize=16, leading=20,
            textColor=colors.HexColor("#172B4D"), spaceBefore=8, spaceAfter=8,
        ),
        "h2": ParagraphStyle(
            "H2", parent=base["Heading2"], fontSize=12, leading=16,
            textColor=colors.HexColor("#1D4ED8"), spaceBefore=8, spaceAfter=5,
        ),
        "body": ParagraphStyle(
            "Body", parent=base["BodyText"], fontSize=9.3, leading=13,
            spaceAfter=6,
        ),
        "small": ParagraphStyle(
            "Small", parent=base["BodyText"], fontSize=7.6, leading=10,
        ),
        "code": ParagraphStyle(
            "Code", fontName="Courier", fontSize=6.6, leading=8.2,
        ),
    }


def page_number(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.drawString(0.55 * inch, 0.35 * inch, "Data Vortex 2026 | Round 1 Phase 2")
    canvas.drawRightString(A4[0] - 0.55 * inch, 0.35 * inch, f"Page {doc.page}")
    canvas.restoreState()


def paragraph(text: str, style: ParagraphStyle) -> Paragraph:
    return Paragraph(text.replace("&", "&amp;"), style)


def results_table(columns: Sequence[str], rows: Sequence[Sequence], width: float) -> LongTable:
    formatted = [list(columns)]
    for row in rows:
        formatted.append([
            f"{value:,}" if isinstance(value, int) else ("" if value is None else str(value))
            for value in row
        ])
    col_width = width / len(columns)
    table = LongTable(formatted, repeatRows=1, colWidths=[col_width] * len(columns))
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#172B4D")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 6.7),
        ("LEADING", (0, 0), (-1, -1), 8.2),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return table


def build_pdf(path: Path, story: list) -> None:
    doc = SimpleDocTemplate(
        str(path), pagesize=A4, rightMargin=0.55 * inch, leftMargin=0.55 * inch,
        topMargin=0.55 * inch, bottomMargin=0.6 * inch,
        title=path.stem.replace("_", " "), author="Data Vortex 2026",
    )
    doc.build(story, onFirstPage=page_number, onLaterPages=page_number)


def cover(title: str, subtitle: str, style: dict[str, ParagraphStyle]) -> list:
    return [
        Spacer(1, 1.65 * inch),
        Paragraph("DATA VORTEX 2026", style["title"]),
        Paragraph("ROUND 1 - PHASE 2", style["title"]),
        Paragraph(title, style["title"]),
        Spacer(1, 0.2 * inch),
        Paragraph(subtitle, style["subtitle"]),
        Paragraph("Prepared from the project SQLite database using read-only SELECT analysis.", style["subtitle"]),
        PageBreak(),
    ]


def make_sql_pdf(results: dict[str, tuple[list[str], list[tuple]]]) -> None:
    style = styles()
    story = cover("FINAL SQL QUERIES", "One selected question at each required difficulty", style)
    for key in ("easy", "medium", "hard"):
        item = QUESTIONS[key]
        story.extend([
            Paragraph(f"{item['difficulty'].upper()} QUESTION - {item['id']}", style["h1"]),
            paragraph(f"<b>Official question:</b> {item['question']}", style["body"]),
            Spacer(1, 5),
            Preformatted(item["sql"], style["code"]),
            Spacer(1, 8),
            paragraph(
                f"Executed successfully against <b>data/data_vortex.db</b>. "
                f"Returned {len(results[key][1]):,} row(s).",
                style["small"],
            ),
            PageBreak() if key != "hard" else Spacer(1, 1),
        ])
    build_pdf(SUBMISSION_DIR / "Data_Vortex_Phase2_SQL_Queries.pdf", story)


def make_logic_pdf(results: dict[str, tuple[list[str], list[tuple]]]) -> None:
    style = styles()
    story = cover("LOGIC EXPLANATION", "Analytical reasoning, validation, and assumptions", style)
    narratives = {
        "easy": [
            ("Analytical objective", "Identify the ten complete-engagement posts with the highest combined interactions."),
            ("Data and filtering", "The posts table supplies the post ID, platform, and interaction columns. The official instruction requires missing likes to be ignored, so WHERE likes IS NOT NULL is applied before ranking."),
            ("Calculation and ordering", "Total engagement is calculated row by row as likes + shares + comments. Ordering descending returns the largest totals; post_id is a deterministic tie-breaker."),
            ("Validation and edge cases", "The query returned exactly 10 rows, all with non-null likes. No joins are used, so there is no risk of duplicate multiplication."),
        ],
        "medium": [
            ("Analytical objective", "Measure the total complete engagement associated with creators at each location."),
            ("Tables and join", "users provides location and posts provides engagement. The one-to-many join uses posts.user_id = users.user_id, the database foreign-key relationship."),
            ("Filtering and aggregation", "Posts with missing likes are excluded because a complete likes + shares + comments total cannot be calculated. GROUP BY location then produces the requested post count and total engagement."),
            ("Validation and edge cases", "Grouped post counts reconcile to the number of posts with non-null likes, and grouped engagement totals reconcile exactly to a direct database-wide total. Every retained post has one matching user."),
        ],
        "hard": [
            ("Analytical objective", "Rank creators within their own locations, then retain the leading three positions per location."),
            ("Transformation", "The first CTE creates one row per user after joining users to posts and aggregating complete engagement. This prevents a creator with many posts from appearing multiple times in the ranking stage."),
            ("Window ranking", "DENSE_RANK partitions by location and orders total engagement descending. The final filter retains engagement_rank <= 3, preserving any genuine ties at a top-three rank."),
            ("Validation and edge cases", "All output ranks are between 1 and 3. The returned row count reconciles to the sum of the first three available ranking positions across locations; the read-only analysis avoids source-database mutation."),
        ],
    }
    for key in ("easy", "medium", "hard"):
        item = QUESTIONS[key]
        story.append(Paragraph(f"{item['difficulty'].upper()} - {item['id']}", style["h1"]))
        story.append(paragraph(f"<b>Official question:</b> {item['question']}", style["body"]))
        for heading, text in narratives[key]:
            story.append(Paragraph(heading, style["h2"]))
            story.append(paragraph(text, style["body"]))
        story.append(paragraph(f"Executed result: <b>{len(results[key][1]):,} row(s)</b> returned.", style["body"]))
        if key != "hard":
            story.append(PageBreak())
    build_pdf(SUBMISSION_DIR / "Data_Vortex_Phase2_Logic_Explanation.pdf", story)


def make_insight_pdf(results: dict[str, tuple[list[str], list[tuple]]]) -> None:
    style = styles()
    easy_rows = results["easy"][1]
    medium_rows = results["medium"][1]
    hard_rows = results["hard"][1]
    easy_top = easy_rows[0]
    medium_top = medium_rows[0]
    hard_top = max(hard_rows, key=lambda row: row[-1])
    story = cover("SQL ANALYTICS & INSIGHTS REPORT", "Selected: 1 Easy Question | 1 Medium Question | 1 Hard Question", style)
    story.extend([
        Paragraph("Executive Summary", style["h1"]),
        paragraph(
            f"This submission analyzes {len(easy_rows):,} leading posts, {len(medium_rows):,} locations, "
            f"and {len(hard_rows):,} location-ranked creator records from the Data Vortex SQLite database. "
            f"The selected questions progress from post-level engagement (E2), to location aggregation (M1), "
            f"to within-location creator ranking (H2).", style["body"]),
        paragraph(
            f"The highest-engagement eligible post is {easy_top[0]} with {easy_top[-1]:,} total interactions. "
            f"The leading location is {medium_top[0]} with {medium_top[2]:,} interactions across {medium_top[1]:,} posts. "
            f"The highest total among the location leaders belongs to {hard_top[2]} in {hard_top[0]} with {hard_top[-1]:,} interactions.", style["body"]),
        PageBreak(),
    ])
    question_summaries = {
        "easy": "Post-level totals expose the individual content items that generated the strongest complete engagement.",
        "medium": "Location aggregation compares creator communities while preserving each post exactly once through the users-to-posts relationship.",
        "hard": "Partitioned ranking distinguishes local leadership from a single global leaderboard and therefore identifies leading creators in every represented location.",
    }
    for key in ("easy", "medium", "hard"):
        item = QUESTIONS[key]
        columns, rows = results[key]
        story.extend([
            Paragraph(f"{item['difficulty'].upper()} QUESTION - {item['id']}", style["h1"]),
            paragraph(f"<b>Official question:</b> {item['question']}", style["body"]),
            Paragraph("Method", style["h2"]),
            paragraph(question_summaries[key], style["body"]),
            Paragraph("Executed Output", style["h2"]),
            results_table(columns, rows, A4[0] - 1.1 * inch),
            Spacer(1, 8),
            Paragraph("Interpretation", style["h2"]),
            paragraph(
                "All displayed values come directly from the executed SELECT query. "
                "Posts with missing likes are excluded so that every engagement total uses all three requested components.",
                style["body"],
            ),
            PageBreak() if key != "hard" else Spacer(1, 1),
        ])
    story.extend([
        PageBreak(),
        Paragraph("Cross-Question Insights", style["h1"]),
        paragraph(
            "The analyses operate at complementary levels: individual posts identify exceptional content, location totals quantify collective output, and the within-location ranking exposes the creators responsible for local leadership. "
            "Because all three use the same complete-engagement rule, their totals are directly comparable without silently treating missing likes as zero.", style["body"]),
        Paragraph("Data Quality and Validation", style["h1"]),
        paragraph(
            "The source database contains 1,500 users and 12,000 posts. SQLite integrity and foreign-key checks pass. "
            "The analysis used a read-only connection; no INSERT, UPDATE, DELETE, DROP, or ALTER statement was issued. "
            "Location totals were reconciled to a direct complete-engagement total, and the location-rank output was checked for valid top-three ranks.", style["body"]),
        Paragraph("Limitations", style["h1"]),
        paragraph(
            "Likes are missing for a subset of posts. Rather than impute a value, this submission excludes those posts whenever an exact total of likes, shares, and comments is required. "
            "The findings describe this dataset and do not establish causal effects of platform, location, or follower count.", style["body"]),
        Paragraph("Conclusion", style["h1"]),
        paragraph(
            "The selected SQL solutions provide a validated view from high-performing posts through location-level contribution to creator leadership. "
            "Together, they demonstrate reproducible aggregation, relational joins, and window-function ranking on the production Data Vortex database.", style["body"]),
    ])
    build_pdf(SUBMISSION_DIR / "Data_Vortex_Phase2_Insight_Report.pdf", story)


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    candidates = [
        Path(os.environ.get("WINDIR", "C:/Windows")) / "Fonts" / ("consolab.ttf" if bold else "consola.ttf"),
        Path(os.environ.get("WINDIR", "C:/Windows")) / "Fonts" / ("arialbd.ttf" if bold else "arial.ttf"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size)
    return ImageFont.load_default()


def make_jpeg(name: str, item: dict, columns: list[str], rows: list[tuple]) -> None:
    """Render executed rows as a clean, self-contained SQL-output screenshot."""
    width, margin, row_height = 1800, 55, 29
    header_height = 130
    question_lines = textwrap.wrap(item["question"], width=145)
    question_height = max(92, 28 + len(question_lines) * 25)
    height = header_height + question_height + (len(rows) + 1) * row_height + 85
    image = Image.new("RGB", (width, height), "#F8FAFC")
    draw = ImageDraw.Draw(image)
    title_font, body_font, mono_font = font(30, True), font(17), font(16)
    draw.rectangle((0, 0, width, header_height), fill="#172B4D")
    draw.text((margin, 26), "DATA VORTEX 2026 | ROUND 1 - PHASE 2", fill="white", font=title_font)
    draw.text((margin, 78), f"EXECUTED SQL OUTPUT - {item['difficulty'].upper()} | {item['id']}", fill="#BFDBFE", font=body_font)
    for line_number, line in enumerate(question_lines):
        draw.text(
            (margin, header_height + 15 + line_number * 25), line,
            fill="#172B4D", font=body_font,
        )
    table_top = header_height + question_height
    available = width - (margin * 2)
    col_width = available // len(columns)
    draw.rectangle((margin, table_top, width - margin, table_top + row_height), fill="#1D4ED8")
    for index, column in enumerate(columns):
        draw.text((margin + index * col_width + 6, table_top + 6), column, fill="white", font=mono_font)
    for row_index, row in enumerate(rows):
        y = table_top + row_height * (row_index + 1)
        if row_index % 2 == 0:
            draw.rectangle((margin, y, width - margin, y + row_height), fill="#EAF2FF")
        for column_index, value in enumerate(row):
            value_text = f"{value:,}" if isinstance(value, int) else str(value)
            draw.text((margin + column_index * col_width + 6, y + 6), value_text, fill="#0F172A", font=mono_font)
    footer = "Source: data/data_vortex.db (read-only) | SQL query executed successfully"
    draw.text((margin, height - 45), footer, fill="#475569", font=body_font)
    image.save(SUBMISSION_DIR / name, "JPEG", quality=92, optimize=True)


def write_manifest() -> None:
    text = """DATA VORTEX 2026 - ROUND 1 PHASE 2
FINAL SUBMISSION MANIFEST

1. SQL Query PDF
   Data_Vortex_Phase2_SQL_Queries.pdf

2. Output Screenshots
   Easy_Output.jpeg
   Medium_Output.jpeg
   Hard_Output.jpeg

3. Logic Explanation PDF
   Data_Vortex_Phase2_Logic_Explanation.pdf

4. Phase 2 Insight Report
   Data_Vortex_Phase2_Insight_Report.pdf

SELECTED QUESTIONS
Easy: E2 - Most Engaged Posts
Medium: M1 - Which Locations Generate the Most Engagement?
Hard: H2 - Rank Users Within Their Location

DATABASE USED:
data/data_vortex.db

VALIDATION:
All three SQL queries executed successfully against the project database.
The database was opened in read-only mode for this analysis.
"""
    (SUBMISSION_DIR / "SUBMISSION_MANIFEST.txt").write_text(text, encoding="utf-8")


def validate_artifacts() -> None:
    required = [
        "Data_Vortex_Phase2_SQL_Queries.pdf",
        "Data_Vortex_Phase2_Logic_Explanation.pdf",
        "Data_Vortex_Phase2_Insight_Report.pdf",
        "Easy_Output.jpeg",
        "Medium_Output.jpeg",
        "Hard_Output.jpeg",
        "SUBMISSION_MANIFEST.txt",
    ]
    for filename in required:
        path = SUBMISSION_DIR / filename
        assert path.exists() and path.stat().st_size > 0, f"Missing artifact: {filename}"
        assert path.stat().st_size < 10 * 1024 * 1024, f"Artifact exceeds 10 MB: {filename}"
    for filename in ("Easy_Output.jpeg", "Medium_Output.jpeg", "Hard_Output.jpeg"):
        with Image.open(SUBMISSION_DIR / filename) as image:
            assert image.format == "JPEG", f"Invalid image format: {filename}"
            image.verify()
    for filename in required[:3]:
        assert (SUBMISSION_DIR / filename).read_bytes()[:4] == b"%PDF", f"Invalid PDF: {filename}"


def main() -> None:
    SUBMISSION_DIR.mkdir(exist_ok=True)
    with read_only_connection() as conn:
        integrity = conn.execute("PRAGMA integrity_check").fetchone()[0]
        foreign_keys = conn.execute("PRAGMA foreign_key_check").fetchall()
        assert integrity == "ok" and not foreign_keys, "Database integrity validation failed"
        results = {key: execute_query(conn, item["sql"]) for key, item in QUESTIONS.items()}
        validate_results(conn, results)
    make_sql_pdf(results)
    make_logic_pdf(results)
    make_insight_pdf(results)
    make_jpeg("Easy_Output.jpeg", QUESTIONS["easy"], *results["easy"])
    make_jpeg("Medium_Output.jpeg", QUESTIONS["medium"], *results["medium"])
    make_jpeg("Hard_Output.jpeg", QUESTIONS["hard"], *results["hard"])
    write_manifest()
    validate_artifacts()
    print(f"Submission package created and validated: {SUBMISSION_DIR}")


if __name__ == "__main__":
    main()
