"""Create the actual, self-contained Round 3 analysis notebook source."""
from __future__ import annotations
from pathlib import Path
import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]

def md(text: str): return nbf.v4.new_markdown_cell(text)
def code(text: str): return nbf.v4.new_code_cell(text)

def build() -> None:
    nb = nbf.v4.new_notebook()
    nb.metadata = {'kernelspec': {'display_name':'Python 3','language':'python','name':'python3'}, 'language_info': {'name':'python'}}
    nb.cells = [
        md("# Data Vortex A'26 — Round 3\n## Public Reaction to Changes in the Recommendation Algorithm\n\n**Team:** hy4366  \\n**Source:** Hacker News public Algolia archive API  \\n**Important limitation:** This is a historical public archive sample collected through the Hacker News Algolia archive API; it is not a continuous live stream."),
        code("from pathlib import Path\nimport json, sys, pandas as pd, matplotlib.pyplot as plt\nfrom IPython.display import display, Image\nROOT = Path.cwd().resolve(); ROOT = ROOT.parent if ROOT.name == 'notebooks' else ROOT\nsys.path.insert(0, str(ROOT/'src'))\nmetadata = json.loads((ROOT/'data/raw/collection_metadata.json').read_text(encoding='utf-8'))\nprint('Collection (UTC):', metadata['collection_start_timestamp'], 'to', metadata['collection_end_timestamp'])\nprint('Raw archive source:', metadata['source'])\nprint('Queries:', '; '.join(metadata['query_terms']))"),
        md("## 1. Dataset loading and data-quality audit\nThe correction pass reuses the saved raw archive export; it does not collect new data."),
        code("raw = pd.read_csv(ROOT/'data/raw/hn_recommendation_algorithm_reactions_raw.csv')\ndf = pd.read_csv(ROOT/'data/processed/round3_recommendation_algorithm_reactions.csv')\nraw['timestamp'] = pd.to_datetime(raw['timestamp'], utc=True)\ndf['timestamp'] = pd.to_datetime(df['timestamp'], utc=True)\naudit = pd.read_csv(ROOT/'results/relevance_filter_audit.csv')\nprint('Raw records:', len(raw), '| final retained:', len(df))\nprint('Observation window:', df.timestamp.min(), 'to', df.timestamp.max())\ndisplay(audit)\ndisplay(pd.DataFrame({'missing_values': df.isna().sum(), 'dtype': df.dtypes.astype(str)}))\nprint('Exact duplicate rows:', df.duplicated().sum(), '| duplicate cleaned text:', df.cleaned_text.duplicated().sum(), '| empty text:', df.text.fillna('').str.strip().eq('').sum())\ndisplay(df[['source','source_type','query_term']].value_counts().to_frame('records').head(15))"),
        md("## 2. Preprocessing and Round 2 NLP model\nRaw text is preserved. The documented stricter relevance screen requires recommendation/feed context plus a concrete change, reaction, quality, or user-control signal. The exact preserved Round 2 TF-IDF + Logistic Regression pipeline is loaded directly."),
        code("import joblib\nmodel = joblib.load(ROOT.parent/'Round-2/models/sentiment_label_pipeline.pkl')\nprint('Model type:', type(model))\nprint('Classes:', model.classes_)\ncheck = model.predict(df.cleaned_text)\nprint('Predictions reproduce saved CSV:', bool((check == df.predicted_sentiment).all()))\ncounts = df.predicted_sentiment.value_counts().reindex(['Positive','Negative','Neutral'], fill_value=0)\ndisplay(pd.DataFrame({'count':counts, 'percent':(counts/len(df)*100).round(2)}))\nImage(filename=str(ROOT/'figures/sentiment_distribution.png'))"),
        md("## 3. Sentiment over time and descriptive candidate shifts\nMonthly index = `(Positive − Negative) / (Positive + Negative + Neutral)`. Candidate shifts require at least three records in each adjacent observed month. Because monthly n is small, these are descriptive candidates, not statistically significant behavioural shifts."),
        code("monthly = pd.read_csv(ROOT/'results/sentiment_by_month.csv')\nshifts = pd.read_csv(ROOT/'results/detected_sentiment_shifts.csv')\ndisplay(monthly[['month','Positive','Negative','Neutral','record_count','sentiment_index']].tail(20))\ndisplay(shifts[['shift_id','start_time','end_time','before_sentiment','after_sentiment','magnitude','record_count_before','record_count_after']])\nfor f in ['sentiment_over_time.png','sentiment_shift_1.png','sentiment_shift_2.png']:\n    display(Image(filename=str(ROOT/'figures'/f)))"),
        md("## 4. Activity and available Hacker News score\n“Engagement” means available Hacker News story score, not a universal social-media engagement measure. The reference baseline is the median monthly total among observed scored months; missing comment scores are not converted to zero."),
        code("activity = pd.read_csv(ROOT/'results/activity_results.csv')\nspikes = pd.read_csv(ROOT/'results/detected_engagement_spikes.csv')\ndisplay(activity.tail(20))\ndisplay(spikes[['spike_id','timestamp_time_window','activity_count','engagement_value','baseline','spike_ratio_or_zscore_or_percentile','evidence_records']])\nfor f in ['data_collection_overview.png','engagement_over_time.png','engagement_spike.png']:\n    display(Image(filename=str(ROOT/'figures'/f)))"),
        md("## 5. Data-derived TF-IDF terms and entities\nTF-IDF uses English and documented custom stopwords. Terms are data-derived keywords, not semantic topic-model labels. Entities use a documented platform/product gazetteer; bare `X` is excluded unless explicit platform context is present."),
        code("topics = pd.read_csv(ROOT/'results/topic_results.csv')\nentities = pd.read_csv(ROOT/'results/entity_results.csv')\ndisplay(topics.head(15))\ndisplay(entities)\nfor f in ['topic_evolution.png','entity_frequency.png']:\n    display(Image(filename=str(ROOT/'figures'/f)))"),
        md("## 6. Trigger evidence, findings, limitations, and conclusion\nEvidence records establish temporal coincidence only. No causal claim is made. The historical archive window, technical-community source, sparse monthly windows, and score-missing comments limit inference."),
        code("evidence = pd.read_csv(ROOT/'results/trigger_evidence.csv')\ndisplay(evidence[['event_id','article_or_post_title','publication_timestamp','url','reason_relevant']])\ndisplay(Image(filename=str(ROOT/'figures/trigger_timeline.png')))\nprint('Findings:')\nprint('- Final retained records:', len(df))\nprint('- Sentiment counts:', counts.to_dict())\nprint('- Descriptive candidate shifts:', shifts[['shift_id','start_time','end_time','magnitude']].to_dict('records'))\nprint('- Highest available-score engagement candidate:', spikes.iloc[0][['timestamp_time_window','engagement_value','baseline']].to_dict())\nprint('Conclusion: Findings are reproducible, source-bound descriptive observations; they do not prove causal public reaction.')")
    ]
    nbf.write(nb, ROOT/'notebooks'/'Round3_Real_Time_Analysis.ipynb')

if __name__ == '__main__': build()
